### ISSUE TITLE
Errors for files named app* in site root directory

### ISSUE THREAD

**Issue by oscarb** [Morendil/github-pages-docker#4]
## Issue

When a file with a filename starting with `app` is placed in the site's root directory, Jekyll is unable to generate the site and returns an error.
## Steps to reproduce
1. Start a  container using the image **morendil/github-pages:latest**
2. Place or create a file with a filename that starts with _app_  in the same directory where `_config.yml` is. For example:
   - apple-touch-icon.png
   - app.md 
## Expected result

Site should be generated with files moved to the `_site` directory
## What happens

Jekyll returns an error:

```
Regenerating: 1 file(s) changed at 2016-09-14 21:22:49 ...error:
       Error: No such file or directory @ rb_sysopen - /apple-touch-icon.png
       Error: Run jekyll build --trace for more information.
```

Running `jekyll build --trace` returns:

```
Configuration file: /app/_config.yml                                                                                                                                               
            Source: /app                                                                                                                                                           
       Destination: /app/_site                                                                                                                                                     
 Incremental build: disabled. Enable with --incremental                                                                                                                            
      Generating...                                                                                                                                                                
/usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/utils.rb:139:in `initialize': No such file or directory @ rb_sysopen - /apple-touch-icon.png (Errno::ENOENT)    
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/utils.rb:139:in `open'                                                                             
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/utils.rb:139:in `has_yaml_header?'                                                                 
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/reader.rb:44:in `block in read_directories'                                                        
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/reader.rb:43:in `select'                                                                           
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/reader.rb:43:in `read_directories'                                                                 
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/reader.rb:17:in `read'                                                                             
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/site.rb:163:in `read'                                                                              
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/site.rb:67:in `process'                                                                            
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/command.rb:26:in `process_site'                                                                    
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/commands/build.rb:63:in `build'                                                                    
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/commands/build.rb:34:in `process'                                                                  
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'                                    
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'                                                                     
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'                                                         
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'                                                                     
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'                                                                  
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'                                                                        
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'                                                                           
        from /usr/local/rvm/gems/ruby-2.1.7@global/gems/jekyll-3.2.1/exe/jekyll:13:in `<top (required)>'                                                                           
        from /usr/local/rvm/gems/ruby-2.1.7@global/bin/jekyll:23:in `load'                                                                                                         
        from /usr/local/rvm/gems/ruby-2.1.7@global/bin/jekyll:23:in `<main>'                                                                                                       
        from /usr/local/rvm/gems/ruby-2.1.7@global/bin/ruby_executable_hooks:15:in `eval'                                                                                          
        from /usr/local/rvm/gems/ruby-2.1.7@global/bin/ruby_executable_hooks:15:in `<main>'
```
## Possible solution

Changing the environment variable `APP_HOME` in the [Dockerfile](https://github.com/Morendil/github-pages-docker/blob/master/Dockerfile#L18) to `/usr/src/app` and building a new Docker image got me a working container. 

I verified that it wasn't an updated gem that got it working by also building a docker with the latest gem dependencies  with `APP_HOME`still being `/app`
## Versions

Error occurs using **morendil/github-pages:latest** with the Jekyll 3.2.1 and `github-pages (94)` on a Synology DS713+.  Ruby is `ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]`

**Comment by Morendil** [comment]
Uh, that's weird. I'm wondering what happens if the "app" directory is named differently, or the variable that holds that value.

Thanks for the heads-up, and the detailed bug report! I'll look into it.

**Comment by Morendil** [comment]
This is a bug in Jekyll: jekyll/jekyll#5276
